name       : coinmp
version    : 1.8.4
release    : 3
source     :
    - https://www.coin-or.org/download/source/CoinMP/CoinMP-1.8.4.tgz : 3459fb0ccbdd39342744684338984ac4cc153fb0434f4cae8cf74bd67490a38d
homepage   : https://projects.coin-or.org/CoinMP
license    : CPL-1.0
component  : programming
summary    : A lightweight API for CLP, CBC, and CGL
description: |
    CoinMP is a C-API interface library that supports most of the functionality of the CLP (Coin LP), CBC (Coin Branch-and-Cut), and CGL (Cut Generation Library) projects.
builddeps  :
    - glpk-devel
    - suitesparse-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/home
