name       : coinmp
version    : 1.8.3
release    : 2
source     :
    - https://www.coin-or.org/download/source/CoinMP/CoinMP-1.8.3.tgz : a1a665db36c7fd69c1e53fffbd108cae1bf22f08acf81c394cd454b8168f22f7
license    : CPL-1.0
component  : programming
summary    : A lightweight API for CLP, CBC, and CGL
description: |
    CoinMP is a C-API interface library that supports most of the functionality of the CLP (Coin LP), CBC (Coin Branch-and-Cut), and CGL (Cut Generation Library) projects.
builddeps  :
    - glpk-devel
    - suitesparse-devel
setup      : |
    %configure 
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/home
